name: TypeScript Builds

on:
  schedule:
    - cron: '22 6 * * *'
  workflow_dispatch:

jobs:
  TypeScript:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        ts-version: [2.x, 3.x, next]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/lockfiles') }}
          
      - name: Install dependencies
        run: yarn
        
      - name: Install TypeScript
        run: yarn add -D typescript@${{ matrix.ts-version }}
      
      - name: Run a multi-line script
        run: |
          echo Add other steps to build,
          echo test, or deploy your project.
